version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-gateway
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: production
    restart: always
